### ISSUE TITLE
Does not handle arrays with repeating values

### ISSUE THREAD

**Issue by sbichenko** [michaelrhodes/closest-to#1]
If you pass an array with repeating values as the second argument, the function will _always_ return the repeating value if the first passed value is larger than the repeating value.

```
var closest = require("closest-to")

console.log(closest(9, [0, 1, 4, 7, 7, 7, 10])) // returns 7
console.log(closest(9, [0, 1, 4, 7, 10])) // returns 10, as it should
```

https://runkit.com/57decda4e62a1c1400b26572/57decda4e62a1c1400b26573/branches/master

**Comment by michaelrhodes** [comment]
Thanks for reporting this, it’s fixed as of 1.0.1
